"""Tests for validate_content helper function."""

import pytest
from fastapi import status, HTTPException
from unittest.mock import patch

from api.dependencies import validate_content


class TestValidateContent:
    """Tests for validate_content helper."""

    def test_valid_content_passes(self):
        """Should not raise for valid content."""
        # Use realistic content that passes the gibberish filter
        validate_content(
            "Should I accept a job offer with higher pay but longer commute?",
            "I have been offered a new job that pays 30% more but requires a 2 hour daily commute. My current job has better work-life balance. What should I consider?",
        )

    def test_empty_title_with_valid_description(self):
        """Should accept empty title with valid description (follow-up pattern)."""
        validate_content(
            "",
            "What if I negotiated remote work options with the new employer?",
        )

    def test_policy_violation_raises_422(self):
        """Should raise HTTPException 422 for content policy violations."""
        from services.content_filter import ContentPolicyError, ViolationType

        with patch("api.dependencies.validate_submission_content") as mock_validate:
            # ContentPolicyError takes violation_type only - message is generated internally
            error = ContentPolicyError(ViolationType.SPAM_GIBBERISH)
            mock_validate.side_effect = error

            with pytest.raises(HTTPException) as exc_info:
                validate_content("title", "description")

            assert exc_info.value.status_code == status.HTTP_422_UNPROCESSABLE_ENTITY
            # Message is generated by ContentPolicyError based on violation type
            assert "clear description" in exc_info.value.detail

    def test_logs_violation_with_context(self):
        """Should log with context and extra fields."""
        from services.content_filter import ContentPolicyError, ViolationType

        with patch("api.dependencies.validate_submission_content") as mock_validate:
            with patch("api.dependencies.logger") as mock_logger:
                mock_validate.side_effect = ContentPolicyError(
                    ViolationType.PROFANITY_ABUSE
                )

                with pytest.raises(HTTPException):
                    validate_content(
                        "title",
                        "description",
                        context="follow-up",
                        case_id="abc-123",
                    )

                mock_logger.warning.assert_called_once()
                call_args = mock_logger.warning.call_args
                assert "follow-up" in call_args[0][0]
                assert call_args[1]["extra"]["case_id"] == "abc-123"
                assert call_args[1]["extra"]["violation_type"] == "profanity_abuse"

    def test_default_context_is_submission(self):
        """Should use 'submission' as default context."""
        from services.content_filter import ContentPolicyError, ViolationType

        with patch("api.dependencies.validate_submission_content") as mock_validate:
            with patch("api.dependencies.logger") as mock_logger:
                mock_validate.side_effect = ContentPolicyError(
                    ViolationType.SPAM_GIBBERISH
                )

                with pytest.raises(HTTPException):
                    validate_content("title", "description")

                call_args = mock_logger.warning.call_args
                assert "submission" in call_args[0][0]
